#!/bin/bash
urle () { [[ "${1}" ]] || return 1; local LANG=C i x; for (( i = 0; i < ${#1}; i++ )); do x="${1:i:1}"; [[ "${x}" == [a-zA-Z0-9.~-] ]] && echo -n "${x}" || printf '%%%02X' "'${x}"; done; echo; }
read -p "Username:" username
read -p "Password:" password
username=$(urle $username)
password=$(urle $password)
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_dips1.tar.gz&resume=1' -O 'Gym_010_dips1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_dips2.tar.gz&resume=1' -O 'Gym_010_dips2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_lunge1.tar.gz&resume=1' -O 'Gym_010_lunge1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_lunge2.tar.gz&resume=1' -O 'Gym_010_lunge2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_mountainclimber1.tar.gz&resume=1' -O 'Gym_010_mountainclimber1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_mountainclimber2.tar.gz&resume=1' -O 'Gym_010_mountainclimber2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_pushup1.tar.gz&resume=1' -O 'Gym_010_pushup1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_pushup2.tar.gz&resume=1' -O 'Gym_010_pushup2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_010_cooking1.tar.gz&resume=1' -O 'Gym_010_cooking1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_burpee2.tar.gz&resume=1' -O 'Gym_011_burpee2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_cooking1.tar.gz&resume=1' -O 'Gym_011_cooking1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_cooking2.tar.gz&resume=1' -O 'Gym_011_cooking2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_dips1.tar.gz&resume=1' -O 'Gym_011_dips1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_dips2.tar.gz&resume=1' -O 'Gym_011_dips2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_dips3.tar.gz&resume=1' -O 'Gym_011_dips3.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_dips4.tar.gz&resume=1' -O 'Gym_011_dips4.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_pushup1.tar.gz&resume=1' -O 'Gym_011_pushup1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_011_pushup2.tar.gz&resume=1' -O 'Gym_011_pushup2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_012_cooking2.tar.gz&resume=1' -O 'Gym_012_cooking2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_012_lunge1.tar.gz&resume=1' -O 'Gym_012_lunge1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_012_lunge2.tar.gz&resume=1' -O 'Gym_012_lunge2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_012_pushup2.tar.gz&resume=1' -O 'Gym_012_pushup2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_burpee4.tar.gz&resume=1' -O 'Gym_013_burpee4.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_dips1.tar.gz&resume=1' -O 'Gym_013_dips1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_dips2.tar.gz&resume=1' -O 'Gym_013_dips2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_dips3.tar.gz&resume=1' -O 'Gym_013_dips3.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_lunge1.tar.gz&resume=1' -O 'Gym_013_lunge1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_lunge2.tar.gz&resume=1' -O 'Gym_013_lunge2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_pushup1.tar.gz&resume=1' -O 'Gym_013_pushup1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/Gym_013_pushup2.tar.gz&resume=1' -O 'Gym_013_pushup2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_009_021_reparingprojector1.tar.gz&resume=1' -O 'LectureHall_009_021_reparingprojector1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_009_sidebalancerun1.tar.gz&resume=1' -O 'LectureHall_009_sidebalancerun1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_010_plankjack1.tar.gz&resume=1' -O 'LectureHall_010_plankjack1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_010_sidebalancerun1.tar.gz&resume=1' -O 'LectureHall_010_sidebalancerun1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_019_wipingchairs1.tar.gz&resume=1' -O 'LectureHall_019_wipingchairs1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_021_plankjack1.tar.gz&resume=1' -O 'LectureHall_021_plankjack1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/LectureHall_021_sidebalancerun1.tar.gz&resume=1' -O 'LectureHall_021_sidebalancerun1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_burpeejump1.tar.gz&resume=1' -O 'ParkingLot2_009_burpeejump1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_burpeejump2.tar.gz&resume=1' -O 'ParkingLot2_009_burpeejump2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_impro1.tar.gz&resume=1' -O 'ParkingLot2_009_impro1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_impro2.tar.gz&resume=1' -O 'ParkingLot2_009_impro2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_impro5.tar.gz&resume=1' -O 'ParkingLot2_009_impro5.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_overfence1.tar.gz&resume=1' -O 'ParkingLot2_009_overfence1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_overfence2.tar.gz&resume=1' -O 'ParkingLot2_009_overfence2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_009_spray1.tar.gz&resume=1' -O 'ParkingLot2_009_spray1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_burpeejump1.tar.gz&resume=1' -O 'ParkingLot2_017_burpeejump1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_burpeejump2.tar.gz&resume=1' -O 'ParkingLot2_017_burpeejump2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_eating1.tar.gz&resume=1' -O 'ParkingLot2_017_eating1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_overfence1.tar.gz&resume=1' -O 'ParkingLot2_017_overfence1.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_overfence2.tar.gz&resume=1' -O 'ParkingLot2_017_overfence2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_pushup2.tar.gz&resume=1' -O 'ParkingLot2_017_pushup2.tar.gz' --no-check-certificate --continue
wget --post-data "username=$username&password=$password" 'https://download.is.tue.mpg.de/download.php?domain=rich&sfile=test/ParkingLot2_017_pushup1.tar.gz&resume=1' -O 'ParkingLot2_017_pushup1.tar.gz' --no-check-certificate --continue
